### PR TITLE
ssh-agent support

### LINKED ISSUE #87: under osx not using ssh-agent
## Affected Version
mole 0.4.0 installed through brew 
MacOS Mojave 10.14.6 (18G95)

## Expected Behavior
mole should use the existing key-agent socket SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.xXxxxX/Listeners

## Current Behavior
asks for key-password

## Steps to Reproduce

1. configure a tunnel
2. start ssh-agent and make sure to set ENV
3. start mole
4. -> key-password is asked

### PR DESCRIPTION
**Pull request by Spitemare**
An ssh-agent started in the traditional way (eval $(ssh-agent)) sets an
environment variable SSH_AUTH_SOCK which points to a unix socket that
the agent listens to. If that environment variable is set add the public
keys in the ssh agent to the list of keys used during authentication.

closes #87

### CODE REVIEW

File: tunnel/tunnel.go [hunk 1]
```diff
@@ -383,10 +385,22 @@ func (t *Tunnel) keepAlive() {
...
 func sshClientConfig(server Server) (*ssh.ClientConfig, error) {
+	var signers []ssh.Signer
+
 	signer, err := server.Key.Parse()
 	if err != nil {
 		return nil, err
 	}
+	signers = append(signers, signer)
+
+	agentAddr := os.Getenv("SSH_AUTH_SOCK")
```
Comment (davrodpin) [inline tunnel/tunnel.go]: I am having mixing feelings about reading that from a environment variable since this is the way the ssh client handles it but all arguments used by mole is either passed as a CLI argument or read from the ssh config file.

So, to keep some consistency on how mole handles things, would you mind adding a new flag where the user can pass the location of the unix socket and add the signers if the flag is present and the socket exists?

Comment (Spitemare) [reply tunnel/tunnel.go]: Flag added. Most often this will just be `--ssh-agent $SSH_AUTH_SOCK` but I can see the reasoning behind wanting a flag. Documentation updated as well.

**Comment by Spitemare** [comment]
The problem with storing the path to the socket is that the socket will change when ssh-agent restarts. Reboot your computer for updates and it's likely the path in the alias config is no longer valid. I have to use a flaky card reader driver that requires me to kill and restart ssh-agent every few days.

We could try to handle it like OpenSSH does in its config. If IdentityAgent is set to a path it always looks there (overriding $SSH_AUTH_SOCK). If the value starts with a '$' it treats it as an environment variable.

**Comment by davrodpin** [comment]
> The problem with storing the path to the socket is that the socket will change when ssh-agent restarts. Reboot your computer for updates and it's likely the path in the alias config is no longer valid. I have to use a flaky card reader driver that requires me to kill and restart ssh-agent every few days.
> 
> We could try to handle it like OpenSSH does in its config. If IdentityAgent is set to a path it always looks there (overriding $SSH_AUTH_SOCK). If the value starts with a '$' it treats it as an environment variable.

If the user want to create an alias specifying the socket path to authenticate through a ssh-agent they would need to make sure the path is always the same probably by using the `-a` flag from `ssh-agent`.
Mole tries to leverage the ssh config file when loading when the user provides a server that matches with one specified on it so it would make totally send to add support for `IdentityAgent`.

**Comment by Spitemare** [comment]
Just a heads up. Github is telling me there's a change requested but I don't see any way to resolve that change. The latest set of commits adds a flag and handles storage.

File: tunnel/tunnel.go [hunk 2]
```diff
@@ -97,11 +102,16 @@ func NewServer(user, address, key string) (*Server, error) {
 		return nil, fmt.Errorf("error while reading key %s: %v", key, err)
 	}
 
+	if strings.HasPrefix(sshAgent, "$") {
+		sshAgent = os.Getenv(sshAgent[1:])
+	}
```
Comment (davrodpin) [inline tunnel/tunnel.go]: What is the idea behind this? Is this common practice?

Comment (Spitemare) [reply tunnel/tunnel.go]: From `man ssh_config`:

>**IdentityAgent**
>Specifies the UNIX-domain socket used to communicate with the authentication agent.
> This option overrides the SSH_AUTH_SOCK environment variable and can be used to select a specific agent.  Setting the socket name to none disables the use of an authentication agent.  If the string "SSH_AUTH_SOCK" is specified, the location of the socket will be read from the SSH_AUTH_SOCK environment variable.  Otherwise if the specified value begins with a `$' character, then it will be treated as an environment variable containing the location of the socket.

This snippet mirrors the behavior of OpenSSH except it does not have a special case for SSH_AUTH_SOCK (no $).

Comment (davrodpin) [reply tunnel/tunnel.go]: Perfect, thanks!

**Comment by trinhan87** [comment]
> An ssh-agent started in the traditional way (eval $(ssh-agent)) sets an
> environment variable SSH_AUTH_SOCK which points to a unix socket that
> the agent listens to. If that environment variable is set add the public
> keys in the ssh agent to the list of keys used during authentication.
> closes #87
